### ISSUE TITLE
dropCharacter.php vulnerable to MySQL injection

### ISSUE THREAD

**Issue by ZappyScript** [rlc0812/osrsWebProject#1]
Your code here: https://github.com/rlc0812/osrsWebProject/blob/master/dropCharacter.php is vulnerable to sql injection.

The vulnerability was found within the lines that look similar too:    
`$dropCharacter = $_POST['btn1'];`    
   
Someone can change the value of $_POST to manipulate your query to update another user status.

Also another vuln found on the same page:     
`$query ="Update memberList SET char$dropCharacter = NULL where (userID =$userID);";`

`$userID` has never been cleaned so this can be manipulated once again to change the full structure of your update query.

Fix for part 1 is to use a whitelist and hard code the variables (since prepared statements cannot be used to bind a column name, only their value)
IE. `$dropCharacter = $_POST['btn1'];`  => `$dropCharacter = "whatever the column name is"` 

Second vuln can be fixed by making the switch to prepared statements:
http://php.net/manual/en/mysqli.prepare.php

These two proposed changes to your code will protect you from nasty SQL attacks.

Never trust anything you get from the client.

Edit: Note that mysqli_real_escape_string should not be used here as that does not protect you against the `$userID` vuln I pointed out before.

These vuln's are not specific to just that code, it's all over your code base. ->prepare && ->bind_param will fix the majority of your vulns here tho.

**Comment by rlc0812** [comment]
Thank you for the feedback! I'll look into this and fix  this when I get home tonight.
